title = "Olof Nord"
baseURL = "/"
DefaultContentLanguage = "en"
license = "GPL-3.0"
licenselink = "https://github.com/olof-nord/olof-nord.github.io/blob/master/LICENSE"
enableGitInfo = true

tags = ["blog", "technical"]

theme = "beautifulhugo"

[Params]
  subtitle = "Software engineer. Open source and privacy guy."
  favicon = "static/favicon.png"
  commit = "https://gitlab.com/olof-nord/olof-nord.gitlab.io/tree/"

[Author]
  name = "Olof Nord"
  github = "olof-nord"
  twitter = "olofnord"
  linkedin = "olofnord"
  xing = "Olof_Nord"

[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 2
