title = "Olof Nord"
baseURL = "https://olof-nord.github.io/"
languageCode = "en-us"
theme = "anubis"

[author]
  name = "Olof Nord"

[menu]
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

