title = "Olof Nord"

baseURL = "/"
defaultContentLanguage = "en"

license = "GPL-3.0"
licenselink = "https://github.com/olof-nord/olof-nord.github.io/blob/master/LICENSE"

enableGitInfo = true
enableRobotsTXT = true

theme = "osprey"

[Params]
  tagline = "Software engineer. Open source and privacy guy."
  author = "Olof Nord"
  description = "Full-stack software engineer based in Berlin, Germany"

  # Social media links in footer
  github = "olof-nord"
  twitter = "olofnord"
  linkedin = "olofnord"
  xing = "Olof_Nord"

  copyright = true
  credit = true
  favicon = "favicon.png"

[[menu.main]]
  name = "About"
  url = "/#about"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 2
