name: Olof Nord GitHub Pages pipeline

on:
  push:
    branches:
      - master

jobs:
  lint-build:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

